---
# tasks file for kodi-mysql

# TODO:
# 1. Add option to force database initialisation even if already exists
#    (Probably use shared variable that is in use in multiple roles)

- name: Install MySQL Server
  apt: name={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - mysql-server
    - python-mysqldb

- name: Create MySQL kodi user for accessing shared databases
  mysql_user: name={{ kodi_mysqldb_user }} password={{ kodi_mysqldb_password }} host={{ item }} priv=*.*:ALL state=present
  with_items:
    - 'localhost'
    - '%'

- name: Get List of MySQL Databases
  command: mysql -e "show databases"
  register: database_list
  changed_when: False

- name: Upload Videos Database Template
  template: src=MyVideos93.sql dest=/tmp/MyVideos93.sql
  when: database_list.stdout.find('MyVideos') == -1

- name: Create empty Videos Database
  mysql_db: name=MyVideos93 state=present
  when: database_list.stdout.find('MyVideos') == -1

- name: Import Initial Videos Database
  mysql_db: name=MyVideos93 state=import target=/tmp/MyVideos93.sql
  when: database_list.stdout.find('MyVideos') == -1

- name: Upload Music Database Template
  template: src=MyMusic52.sql dest=/tmp/MyMusic52.sql
  when: database_list.stdout.find('MyMusic') == -1

- name: Create empty Music Database
  mysql_db: name=MyMusic52 state=present
  when: database_list.stdout.find('MyMusic') == -1

- name: Import Initial Music Database
  mysql_db: name=MyMusic52 state=import target=/tmp/MyMusic52.sql
  when: database_list.stdout.find('MyMusic') == -1

- name: Make sure MySQL is listening on all interfaces
  lineinfile: dest=/etc/mysql/my.cnf regexp="^bind-address" line='bind-address            = 0.0.0.0' state=present
  notify:
    - restart mysql

- name: Make sure MySQL is running and started on boot
  service: name=mysql state=started enabled=yes

- meta: flush_handlers
